### ISSUE TITLE
Bug in corsCheck

### ISSUE THREAD

**Issue by JohannesFluegel** [gs1/GS1DL-resolver-testsuite#12]
https://github.com/gs1/GS1DL-resolver-testsuite/blob/master/GS1DigitalLinkResolverTestSuite.js#L268

Change `if (data.result['access-control-allow-origin'] !== '')` simply into `if (data.result['access-control-allow-origin'])`.
If this header is not set, it will result into _undefined_ instead of _empty string_. And _undefined_ always unequals _empty string_.

**Comment by philarcher** [comment]
Thank you @JohannesFluegel!
